"""status Table updated

Revision ID: 0587c40f115a
Revises: da5b26cf48ad
Create Date: 2026-03-08 11:48:15.400343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0587c40f115a'
down_revision: Union[str, Sequence[str], None] = 'da5b26cf48ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("UPDATE \"user\" SET password = 'temp_password' WHERE password IS NULL")
    # op.add_column('status', sa.Column('status_type', sa.String(), nullable=True))
    # op.alter_column('user', 'password',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('user', 'password',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.drop_column('status', 'status_type')
    # ### end Alembic commands ###
