"""Faulty Entity Table update

Revision ID: 0cd15f8fecdb
Revises: b5d139903bb1
Create Date: 2026-05-19 01:25:01.238002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd15f8fecdb'
down_revision: Union[str, Sequence[str], None] = 'b5d139903bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faulty_entity', 'entity_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('faulty_entity', 'part_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('faulty_entity', 'serial_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('faulty_entity', 'parent_entity_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('faulty_entity', 'confirmed_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('faulty_entity', 'investigation_notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('faulty_entity', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('faulty_entity', 'updated_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('maintenance_case', 'case_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintenance_case', 'case_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('faulty_entity', 'updated_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('faulty_entity', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('faulty_entity', 'investigation_notes',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('faulty_entity', 'confirmed_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('faulty_entity', 'parent_entity_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('faulty_entity', 'serial_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('faulty_entity', 'part_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('faulty_entity', 'entity_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
