"""Status Table name-> status_name 

Revision ID: 142959916d44
Revises: 9404410165fe
Create Date: 2026-06-19 21:49:21.198016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '142959916d44'
down_revision: Union[str, Sequence[str], None] = '9404410165fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'status_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('order', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'order_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('order', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('status', sa.Column('status_name', sa.String(), nullable=True))
    op.drop_column('status', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('status', 'status_name')
    op.alter_column('order', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'order_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('order', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('customer', 'status_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
