"""maintenance_case.project_name

Revision ID: 2cc06ace22e1
Revises: 7fe35679de66
Create Date: 2026-06-15 04:38:38.809349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc06ace22e1'
down_revision: Union[str, Sequence[str], None] = '7fe35679de66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_case', sa.Column('project_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_case', 'project_name')
    # ### end Alembic commands ###
