"""Upgraded Maintenance tables

Revision ID: 3741067e1523
Revises: a22834f7dafb
Create Date: 2026-05-16 11:18:03.970963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3741067e1523'
down_revision: Union[str, Sequence[str], None] = 'a22834f7dafb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_component_configuration_item'), table_name='component')
    op.drop_index(op.f('idx_component_part_number'), table_name='component')
    op.drop_index(op.f('idx_component_serial_number'), table_name='component')
    op.execute("""
    DO $$
    BEGIN
        ALTER TYPE entitytype RENAME VALUE 'PROJECT' TO 'project';
        ALTER TYPE entitytype RENAME VALUE 'SYSTEM' TO 'system';
        ALTER TYPE entitytype RENAME VALUE 'SUBSYSTEM' TO 'subsystem';
        ALTER TYPE entitytype RENAME VALUE 'MODULE' TO 'module';
        ALTER TYPE entitytype RENAME VALUE 'UNIT' TO 'unit';
        ALTER TYPE entitytype RENAME VALUE 'COMPONENT' TO 'component';
        ALTER TYPE entitytype RENAME VALUE 'ORDER' TO 'order';
        ALTER TYPE entitytype RENAME VALUE 'CUSTOMER' TO 'customer';

        ALTER TYPE faultyentitystatus RENAME VALUE 'IDENTIFIED' TO 'identified';
        ALTER TYPE faultyentitystatus RENAME VALUE 'UNDER_INSPECTION' TO 'under_inspection';
        ALTER TYPE faultyentitystatus RENAME VALUE 'CONFIRMED_FAULTY' TO 'confirmed_faulty';
        ALTER TYPE faultyentitystatus RENAME VALUE 'RESOLVED' TO 'resolved';
        ALTER TYPE faultyentitystatus RENAME VALUE 'NO_FAULT_FOUND' TO 'no_fault_found';

        ALTER TYPE resolutiontype RENAME VALUE 'REPAIRED' TO 'repaired';
        ALTER TYPE resolutiontype RENAME VALUE 'REPLACED' TO 'replaced';
        ALTER TYPE resolutiontype RENAME VALUE 'NO_FAULT_FOUND' TO 'no_fault_found';
        ALTER TYPE resolutiontype RENAME VALUE 'DECOMMISSIONED' TO 'decommissioned';

        ALTER TYPE actiontype RENAME VALUE 'INSPECTION' TO 'inspection';
        ALTER TYPE actiontype RENAME VALUE 'DISASSEMBLY' TO 'disassembly';
        ALTER TYPE actiontype RENAME VALUE 'REPAIR' TO 'repair';
        ALTER TYPE actiontype RENAME VALUE 'REPLACEMENT' TO 'replacement';
        ALTER TYPE actiontype RENAME VALUE 'TESTING' TO 'testing';
        ALTER TYPE actiontype RENAME VALUE 'CLEANING' TO 'cleaning';
        ALTER TYPE actiontype RENAME VALUE 'RECALIBRATION' TO 'recalibration';

        ALTER TYPE casestatus RENAME VALUE 'OPEN' TO 'open';
        ALTER TYPE casestatus RENAME VALUE 'UNDER_INSPECTION' TO 'under_inspection';
        ALTER TYPE casestatus RENAME VALUE 'UNDER_REPAIR' TO 'under_repair';
        ALTER TYPE casestatus RENAME VALUE 'RESOLVED' TO 'resolved';
        ALTER TYPE casestatus RENAME VALUE 'CLOSED' TO 'closed';

        ALTER TYPE deliverystatus RENAME VALUE 'PENDING' TO 'pending';
        ALTER TYPE deliverystatus RENAME VALUE 'DISPATCHED' TO 'dispatched';
        ALTER TYPE deliverystatus RENAME VALUE 'DELIVERED' TO 'delivered';
        ALTER TYPE deliverystatus RENAME VALUE 'CONFIRMED_BY_CUSTOMER' TO 'confirmed_by_customer';
    EXCEPTION WHEN undefined_object OR duplicate_object THEN
        NULL;
    END
    $$;
    """)
    op.add_column('faulty_entity', sa.Column('fault_type', sa.Enum('hardware', 'software', 'physical_damage', 'wear', 'manufacturing_defect', 'unclassified', name='faulttype'), nullable=False))
    op.add_column('faulty_entity', sa.Column('fault_description', sa.String(), nullable=True))
    op.add_column('faulty_entity', sa.Column('status', sa.Enum('identified', 'under_inspection', 'confirmed_faulty', 'resolved', 'no_fault_found', name='faultyentitystatus'), nullable=False))
    op.add_column('faulty_entity', sa.Column('resolution_type', sa.Enum('repaired', 'replaced', 'no_fault_found', 'decommissioned', name='resolutiontype'), nullable=True))
    op.add_column('faulty_entity', sa.Column('identified_at', sa.DateTime(), nullable=False))
    op.add_column('faulty_entity', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.alter_column('faulty_entity', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('project', 'system', 'subsystem', 'module', 'unit', 'component', 'order', 'customer', name='entitytype'),
               nullable=False,
               postgresql_using='lower(entity_type)::entitytype')
    op.alter_column('faulty_entity', 'entity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('idx_faulty_entity_case_id'), table_name='faulty_entity')
    op.drop_index(op.f('idx_faulty_entity_entity_id'), table_name='faulty_entity')
    op.drop_index(op.f('idx_faulty_entity_entity_type'), table_name='faulty_entity')
    op.drop_index(op.f('idx_faulty_entity_identified_by'), table_name='faulty_entity')
    op.drop_index(op.f('idx_faulty_entity_parent'), table_name='faulty_entity')
    op.create_index(op.f('ix_faulty_entity_case_id'), 'faulty_entity', ['case_id'], unique=False)
    op.drop_constraint(op.f('fk_faulty_entity_case'), 'faulty_entity', type_='foreignkey')
    op.drop_constraint(op.f('fk_faulty_entity_identified_by'), 'faulty_entity', type_='foreignkey')
    op.drop_constraint(op.f('fk_faulty_entity_parent'), 'faulty_entity', type_='foreignkey')
    op.create_foreign_key(None, 'faulty_entity', 'maintenance_case', ['case_id'], ['id'])
    op.create_foreign_key(None, 'faulty_entity', 'faulty_entity', ['parent_faulty_entity_id'], ['id'])
    op.create_foreign_key(None, 'faulty_entity', 'user', ['identified_by'], ['id'])
    op.drop_table_comment(
        'faulty_entity',
        existing_comment='Stores all faulty entities involved in a maintenance case including cascade hierarchy.',
        schema=None
    )
    op.drop_column('faulty_entity', 'created_at')
    op.drop_column('faulty_entity', 'remarks')
    op.drop_column('faulty_entity', 'fault_type ')
    op.add_column('maintenance_action', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('maintenance_action', sa.Column('outcome', sa.Enum('pass', 'fail', 'inconclusive', 'pending', name='actionoutcome'), nullable=True))
    op.add_column('maintenance_action', sa.Column('replacement_entity_id', sa.Integer(), nullable=True))
    op.add_column('maintenance_action', sa.Column('replacement_entity_type', sa.Enum('project', 'system', 'subsystem', 'module', 'unit', 'component', 'order', 'customer', name='entitytype'), nullable=True))
    op.alter_column('maintenance_action', 'action_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('inspection', 'disassembly', 'repair', 'replacement', 'testing', 'cleaning', 'recalibration', name='actiontype'),
               nullable=False,
               postgresql_using='lower(action_type)::actiontype')
    op.alter_column('maintenance_action', 'performed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_maintenance_action_faulty_entity_id'), table_name='maintenance_action')
    op.drop_index(op.f('idx_maintenance_action_performed_by'), table_name='maintenance_action')
    op.create_index(op.f('ix_maintenance_action_faulty_entity_id'), 'maintenance_action', ['faulty_entity_id'], unique=False)
    op.drop_constraint(op.f('fk_maintenance_action_faulty_entity'), 'maintenance_action', type_='foreignkey')
    op.drop_constraint(op.f('fk_maintenance_action_performed_by'), 'maintenance_action', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_action', 'user', ['performed_by'], ['id'])
    op.create_foreign_key(None, 'maintenance_action', 'faulty_entity', ['faulty_entity_id'], ['id'])
    op.drop_table_comment(
        'maintenance_action',
        existing_comment='Stores actions performed against faulty entities.',
        schema=None
    )
    op.drop_column('maintenance_action', 'action_details')
    op.alter_column('maintenance_case', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.execute("ALTER TABLE maintenance_case ALTER COLUMN status DROP DEFAULT")
    op.alter_column('maintenance_case', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('open', 'under_inspection', 'under_repair', 'resolved', 'closed', name='casestatus'),
               nullable=False,
               existing_server_default=sa.text("'OPEN'::character varying"),
               server_default=sa.text("'open'::casestatus"),
               postgresql_using='lower(status)::casestatus')
    op.alter_column('maintenance_case', 'resolution_notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('maintenance_case', 'reported_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('maintenance_case', 'closed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_maintenance_case_case_number'), table_name='maintenance_case')
    op.drop_index(op.f('idx_maintenance_case_project_id'), table_name='maintenance_case')
    op.drop_index(op.f('idx_maintenance_case_reported_at'), table_name='maintenance_case')
    op.drop_index(op.f('idx_maintenance_case_reported_by'), table_name='maintenance_case')
    op.drop_index(op.f('idx_maintenance_case_status'), table_name='maintenance_case')
    op.drop_constraint(op.f('maintenance_case_case_number_key'), 'maintenance_case', type_='unique')
    op.create_index(op.f('ix_maintenance_case_case_number'), 'maintenance_case', ['case_number'], unique=True)
    op.drop_constraint(op.f('fk_maintenance_case_reported_by'), 'maintenance_case', type_='foreignkey')
    op.drop_constraint(op.f('fk_maintenance_case_project'), 'maintenance_case', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_case', 'user', ['reported_by'], ['id'])
    op.create_foreign_key(None, 'maintenance_case', 'project', ['project_id'], ['id'])
    op.drop_table_comment(
        'maintenance_case',
        existing_comment='Stores maintenance fault cases reported after project delivery.',
        schema=None
    )
    op.drop_column('maintenance_case', 'created_at')
    op.add_column('maintenance_delivery', sa.Column('delivery_type', sa.Enum('initial_delivery', 're_delivery', 'partial_re_delivery', name='deliverytype'), nullable=False))
    op.add_column('maintenance_delivery', sa.Column('status', sa.Enum('pending', 'dispatched', 'delivered', 'confirmed_by_customer', name='deliverystatus'), nullable=False))
    op.add_column('maintenance_delivery', sa.Column('received_by', sa.String(), nullable=True))
    op.add_column('maintenance_delivery', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('maintenance_delivery', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.alter_column('maintenance_delivery', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_maintenance_delivery_case_id'), table_name='maintenance_delivery')
    op.drop_index(op.f('idx_maintenance_delivery_delivered_by'), table_name='maintenance_delivery')
    op.drop_index(op.f('idx_maintenance_delivery_dispatch_number'), table_name='maintenance_delivery')
    op.create_index(op.f('ix_maintenance_delivery_case_id'), 'maintenance_delivery', ['case_id'], unique=False)
    op.drop_constraint(op.f('fk_maintenance_delivery_delivered_by'), 'maintenance_delivery', type_='foreignkey')
    op.drop_constraint(op.f('fk_maintenance_delivery_case'), 'maintenance_delivery', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_delivery', 'user', ['delivered_by'], ['id'])
    op.create_foreign_key(None, 'maintenance_delivery', 'maintenance_case', ['case_id'], ['id'])
    op.drop_table_comment(
        'maintenance_delivery',
        existing_comment='Stores dispatch/delivery records related to maintenance cases.',
        schema=None
    )
    op.drop_column('maintenance_delivery', 'dispatch_number')
    op.drop_column('maintenance_delivery', 'delivery_status')
    op.drop_column('maintenance_delivery', 'remarks')
    op.drop_index(op.f('idx_module_configuration_item'), table_name='module')
    op.drop_index(op.f('idx_module_part_number'), table_name='module')
    op.drop_index(op.f('idx_module_serial_number'), table_name='module')
    op.drop_index(op.f('idx_subsystem_configuration_item'), table_name='subsystem')
    op.drop_index(op.f('idx_subsystem_part_number'), table_name='subsystem')
    op.drop_index(op.f('idx_subsystem_serial_number'), table_name='subsystem')
    op.drop_index(op.f('idx_system_configuration_item'), table_name='system')
    op.drop_index(op.f('idx_system_part_number'), table_name='system')
    op.drop_index(op.f('idx_system_serial_number'), table_name='system')
    op.drop_index(op.f('idx_unit_configuration_item'), table_name='unit')
    op.drop_index(op.f('idx_unit_part_number'), table_name='unit')
    op.drop_index(op.f('idx_unit_serial_number'), table_name='unit')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_unit_serial_number'), 'unit', ['serial_number'], unique=False)
    op.create_index(op.f('idx_unit_part_number'), 'unit', ['part_number'], unique=False)
    op.create_index(op.f('idx_unit_configuration_item'), 'unit', ['configuration_item'], unique=False)
    op.create_index(op.f('idx_system_serial_number'), 'system', ['serial_number'], unique=False)
    op.create_index(op.f('idx_system_part_number'), 'system', ['part_number'], unique=False)
    op.create_index(op.f('idx_system_configuration_item'), 'system', ['configuration_item'], unique=False)
    op.create_index(op.f('idx_subsystem_serial_number'), 'subsystem', ['serial_number'], unique=False)
    op.create_index(op.f('idx_subsystem_part_number'), 'subsystem', ['part_number'], unique=False)
    op.create_index(op.f('idx_subsystem_configuration_item'), 'subsystem', ['configuration_item'], unique=False)
    op.create_index(op.f('idx_module_serial_number'), 'module', ['serial_number'], unique=False)
    op.create_index(op.f('idx_module_part_number'), 'module', ['part_number'], unique=False)
    op.create_index(op.f('idx_module_configuration_item'), 'module', ['configuration_item'], unique=False)
    op.add_column('maintenance_delivery', sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('maintenance_delivery', sa.Column('delivery_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('maintenance_delivery', sa.Column('dispatch_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_table_comment(
        'maintenance_delivery',
        'Stores dispatch/delivery records related to maintenance cases.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'maintenance_delivery', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_delivery', type_='foreignkey')
    op.create_foreign_key(op.f('fk_maintenance_delivery_case'), 'maintenance_delivery', 'maintenance_case', ['case_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_maintenance_delivery_delivered_by'), 'maintenance_delivery', 'user', ['delivered_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_maintenance_delivery_case_id'), table_name='maintenance_delivery')
    op.create_index(op.f('idx_maintenance_delivery_dispatch_number'), 'maintenance_delivery', ['dispatch_number'], unique=False)
    op.create_index(op.f('idx_maintenance_delivery_delivered_by'), 'maintenance_delivery', ['delivered_by'], unique=False)
    op.create_index(op.f('idx_maintenance_delivery_case_id'), 'maintenance_delivery', ['case_id'], unique=False)
    op.alter_column('maintenance_delivery', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('maintenance_delivery', 'delivered_at')
    op.drop_column('maintenance_delivery', 'notes')
    op.drop_column('maintenance_delivery', 'received_by')
    op.drop_column('maintenance_delivery', 'status')
    op.drop_column('maintenance_delivery', 'delivery_type')
    op.add_column('maintenance_case', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.create_table_comment(
        'maintenance_case',
        'Stores maintenance fault cases reported after project delivery.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'maintenance_case', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_case', type_='foreignkey')
    op.create_foreign_key(op.f('fk_maintenance_case_project'), 'maintenance_case', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_maintenance_case_reported_by'), 'maintenance_case', 'user', ['reported_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_maintenance_case_case_number'), table_name='maintenance_case')
    op.create_unique_constraint(op.f('maintenance_case_case_number_key'), 'maintenance_case', ['case_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_maintenance_case_status'), 'maintenance_case', ['status'], unique=False)
    op.create_index(op.f('idx_maintenance_case_reported_by'), 'maintenance_case', ['reported_by'], unique=False)
    op.create_index(op.f('idx_maintenance_case_reported_at'), 'maintenance_case', ['reported_at'], unique=False)
    op.create_index(op.f('idx_maintenance_case_project_id'), 'maintenance_case', ['project_id'], unique=False)
    op.create_index(op.f('idx_maintenance_case_case_number'), 'maintenance_case', ['case_number'], unique=False)
    op.alter_column('maintenance_case', 'closed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('maintenance_case', 'reported_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('maintenance_case', 'resolution_notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('maintenance_case', 'status',
               existing_type=sa.Enum('open', 'under_inspection', 'under_repair', 'resolved', 'closed', name='casestatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'OPEN'::character varying"))
    op.alter_column('maintenance_case', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('maintenance_action', sa.Column('action_details', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table_comment(
        'maintenance_action',
        'Stores actions performed against faulty entities.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'maintenance_action', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_action', type_='foreignkey')
    op.create_foreign_key(op.f('fk_maintenance_action_performed_by'), 'maintenance_action', 'user', ['performed_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_maintenance_action_faulty_entity'), 'maintenance_action', 'faulty_entity', ['faulty_entity_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_maintenance_action_faulty_entity_id'), table_name='maintenance_action')
    op.create_index(op.f('idx_maintenance_action_performed_by'), 'maintenance_action', ['performed_by'], unique=False)
    op.create_index(op.f('idx_maintenance_action_faulty_entity_id'), 'maintenance_action', ['faulty_entity_id'], unique=False)
    op.alter_column('maintenance_action', 'performed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('maintenance_action', 'action_type',
               existing_type=sa.Enum('inspection', 'disassembly', 'repair', 'replacement', 'testing', 'cleaning', 'recalibration', name='actiontype'),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('maintenance_action', 'replacement_entity_type')
    op.drop_column('maintenance_action', 'replacement_entity_id')
    op.drop_column('maintenance_action', 'outcome')
    op.drop_column('maintenance_action', 'notes')
    op.add_column('faulty_entity', sa.Column('fault_type ', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('faulty_entity', sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('faulty_entity', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.create_table_comment(
        'faulty_entity',
        'Stores all faulty entities involved in a maintenance case including cascade hierarchy.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'faulty_entity', type_='foreignkey')
    op.drop_constraint(None, 'faulty_entity', type_='foreignkey')
    op.drop_constraint(None, 'faulty_entity', type_='foreignkey')
    op.create_foreign_key(op.f('fk_faulty_entity_parent'), 'faulty_entity', 'faulty_entity', ['parent_faulty_entity_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_faulty_entity_identified_by'), 'faulty_entity', 'user', ['identified_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_faulty_entity_case'), 'faulty_entity', 'maintenance_case', ['case_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_faulty_entity_case_id'), table_name='faulty_entity')
    op.create_index(op.f('idx_faulty_entity_parent'), 'faulty_entity', ['parent_faulty_entity_id'], unique=False)
    op.create_index(op.f('idx_faulty_entity_identified_by'), 'faulty_entity', ['identified_by'], unique=False)
    op.create_index(op.f('idx_faulty_entity_entity_type'), 'faulty_entity', ['entity_type'], unique=False)
    op.create_index(op.f('idx_faulty_entity_entity_id'), 'faulty_entity', ['entity_id'], unique=False)
    op.create_index(op.f('idx_faulty_entity_case_id'), 'faulty_entity', ['case_id'], unique=False)
    op.alter_column('faulty_entity', 'entity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('faulty_entity', 'entity_type',
               existing_type=sa.Enum('project', 'system', 'subsystem', 'module', 'unit', 'component', 'order', 'customer', name='entitytype'),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('faulty_entity', 'resolved_at')
    op.drop_column('faulty_entity', 'identified_at')
    op.drop_column('faulty_entity', 'resolution_type')
    op.drop_column('faulty_entity', 'status')
    op.drop_column('faulty_entity', 'fault_description')
    op.drop_column('faulty_entity', 'fault_type')
    op.create_index(op.f('idx_component_serial_number'), 'component', ['serial_number'], unique=False)
    op.create_index(op.f('idx_component_part_number'), 'component', ['part_number'], unique=False)
    op.create_index(op.f('idx_component_configuration_item'), 'component', ['configuration_item'], unique=False)
    # ### end Alembic commands ###
