"""Missing Cascade delete included

Revision ID: 3e9e1ea7d2a1
Revises: 4bc8282302b3
Create Date: 2026-06-20 09:27:33.841259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9e1ea7d2a1'
down_revision: Union[str, Sequence[str], None] = '4bc8282302b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('faulty_entity_case_id_fkey'), 'faulty_entity', type_='foreignkey')
    op.create_foreign_key(None, 'faulty_entity', 'maintenance_case', ['case_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('maintenance_action_faulty_entity_id_fkey'), 'maintenance_action', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_action', 'faulty_entity', ['faulty_entity_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('maintenance_case_project_id_fkey'), 'maintenance_case', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_case', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('maintenance_delivery_case_id_fkey'), 'maintenance_delivery', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_delivery', 'maintenance_case', ['case_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'maintenance_delivery', type_='foreignkey')
    op.create_foreign_key(op.f('maintenance_delivery_case_id_fkey'), 'maintenance_delivery', 'maintenance_case', ['case_id'], ['id'])
    op.drop_constraint(None, 'maintenance_case', type_='foreignkey')
    op.create_foreign_key(op.f('maintenance_case_project_id_fkey'), 'maintenance_case', 'project', ['project_id'], ['id'])
    op.drop_constraint(None, 'maintenance_action', type_='foreignkey')
    op.create_foreign_key(op.f('maintenance_action_faulty_entity_id_fkey'), 'maintenance_action', 'faulty_entity', ['faulty_entity_id'], ['id'])
    op.drop_constraint(None, 'faulty_entity', type_='foreignkey')
    op.create_foreign_key(op.f('faulty_entity_case_id_fkey'), 'faulty_entity', 'maintenance_case', ['case_id'], ['id'])
    # ### end Alembic commands ###
