"""Missing Cascade delete included

Revision ID: 4bc8282302b3
Revises: 4ed87f46172c
Create Date: 2026-06-20 09:22:59.823401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc8282302b3'
down_revision: Union[str, Sequence[str], None] = '4ed87f46172c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_customer_id_fkey'), 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'customer', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key(op.f('order_customer_id_fkey'), 'order', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###
