"""Cascade delete in all parent child relations included 

Revision ID: 4ed87f46172c
Revises: 199bac76aa37
Create Date: 2026-06-20 09:19:03.446243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed87f46172c'
down_revision: Union[str, Sequence[str], None] = '199bac76aa37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('component_unit_id_fkey'), 'component', type_='foreignkey')
    op.create_foreign_key(None, 'component', 'unit', ['unit_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('module_subsystem_id_fkey'), 'module', type_='foreignkey')
    op.create_foreign_key(None, 'module', 'subsystem', ['subsystem_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_order_id_fkey'), 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('subsystem_system_id_fkey'), 'subsystem', type_='foreignkey')
    op.drop_constraint(op.f('subsystem_status_id_fkey'), 'subsystem', type_='foreignkey')
    op.create_foreign_key(None, 'subsystem', 'system', ['system_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subsystem', 'status', ['status_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('system_project_id_fkey'), 'system', type_='foreignkey')
    op.create_foreign_key(None, 'system', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('unit_module_id_fkey'), 'unit', type_='foreignkey')
    op.create_foreign_key(None, 'unit', 'module', ['module_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit', type_='foreignkey')
    op.create_foreign_key(op.f('unit_module_id_fkey'), 'unit', 'module', ['module_id'], ['id'])
    op.drop_constraint(None, 'system', type_='foreignkey')
    op.create_foreign_key(op.f('system_project_id_fkey'), 'system', 'project', ['project_id'], ['id'])
    op.drop_constraint(None, 'subsystem', type_='foreignkey')
    op.drop_constraint(None, 'subsystem', type_='foreignkey')
    op.create_foreign_key(op.f('subsystem_status_id_fkey'), 'subsystem', 'status', ['status_id'], ['id'])
    op.create_foreign_key(op.f('subsystem_system_id_fkey'), 'subsystem', 'system', ['system_id'], ['id'])
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key(op.f('project_order_id_fkey'), 'project', 'order', ['order_id'], ['id'])
    op.drop_constraint(None, 'module', type_='foreignkey')
    op.create_foreign_key(op.f('module_subsystem_id_fkey'), 'module', 'subsystem', ['subsystem_id'], ['id'])
    op.drop_constraint(None, 'component', type_='foreignkey')
    op.create_foreign_key(op.f('component_unit_id_fkey'), 'component', 'unit', ['unit_id'], ['id'])
    # ### end Alembic commands ###
