"""Added column

Revision ID: 57c72579c8d6
Revises: a22834f7dafb
Create Date: 2026-06-02 15:00:51.737702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c72579c8d6'
down_revision: Union[str, Sequence[str], None] = 'a22834f7dafb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('component', sa.Column('part_number', sa.String(), nullable=True))
    op.add_column('component', sa.Column('serial_number', sa.String(), nullable=True))
    op.add_column('component', sa.Column('configuration_item', sa.String(), nullable=True))
    op.add_column('module', sa.Column('part_number', sa.String(), nullable=True))
    op.add_column('module', sa.Column('serial_number', sa.String(), nullable=True))
    op.add_column('module', sa.Column('configuration_item', sa.String(), nullable=True))
    op.add_column('subsystem', sa.Column('part_number', sa.String(), nullable=True))
    op.add_column('subsystem', sa.Column('serial_number', sa.String(), nullable=True))
    op.add_column('subsystem', sa.Column('configuration_item', sa.String(), nullable=True))
    op.add_column('system', sa.Column('part_number', sa.String(), nullable=True))
    op.add_column('system', sa.Column('serial_number', sa.String(), nullable=True))
    op.add_column('system', sa.Column('configuration_item', sa.String(), nullable=True))
    op.add_column('unit', sa.Column('part_number', sa.String(), nullable=True))
    op.add_column('unit', sa.Column('serial_number', sa.String(), nullable=True))
    op.add_column('unit', sa.Column('configuration_item', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'configuration_item')
    op.drop_column('unit', 'serial_number')
    op.drop_column('unit', 'part_number')
    op.drop_column('system', 'configuration_item')
    op.drop_column('system', 'serial_number')
    op.drop_column('system', 'part_number')
    op.drop_column('subsystem', 'configuration_item')
    op.drop_column('subsystem', 'serial_number')
    op.drop_column('subsystem', 'part_number')
    op.drop_column('module', 'configuration_item')
    op.drop_column('module', 'serial_number')
    op.drop_column('module', 'part_number')
    op.drop_column('component', 'configuration_item')
    op.drop_column('component', 'serial_number')
    op.drop_column('component', 'part_number')
    # ### end Alembic commands ###
