"""Customer table New fields added 

Revision ID: 5e3c33c3d66e
Revises: 2cc06ace22e1
Create Date: 2026-06-17 03:41:33.653445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e3c33c3d66e'
down_revision: Union[str, Sequence[str], None] = '2cc06ace22e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('customer_code', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('organization_type', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('primary_contact_name', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('designation', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('email', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('website', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('address', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('country', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('status', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_customer_customer_code'), 'customer', ['customer_code'], unique=True)
    op.drop_column('customer', 'contact_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('contact_info', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_customer_customer_code'), table_name='customer')
    op.drop_column('customer', 'updated_at')
    op.drop_column('customer', 'created_by')
    op.drop_column('customer', 'status')
    op.drop_column('customer', 'notes')
    op.drop_column('customer', 'country')
    op.drop_column('customer', 'address')
    op.drop_column('customer', 'website')
    op.drop_column('customer', 'phone')
    op.drop_column('customer', 'email')
    op.drop_column('customer', 'designation')
    op.drop_column('customer', 'primary_contact_name')
    op.drop_column('customer', 'organization_type')
    op.drop_column('customer', 'customer_code')
    # ### end Alembic commands ###
