"""faulty entities table updated

Revision ID: 6159b971c73e
Revises: d671fa45ec45
Create Date: 2026-06-15 03:53:41.147781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6159b971c73e'
down_revision: Union[str, Sequence[str], None] = 'd671fa45ec45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faulty_entity', sa.Column('parent_entity_id', sa.Integer(), nullable=True))
    op.add_column('faulty_entity', sa.Column('parent_entity_type', sa.Enum('PROJECT', 'SYSTEM', 'SUBSYSTEM', 'MODULE', 'UNIT', 'COMPONENT', 'ORDER', 'CUSTOMER', name='entitytype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faulty_entity', 'parent_entity_type')
    op.drop_column('faulty_entity', 'parent_entity_id')
    # ### end Alembic commands ###
