"""Added New Columns in Fault Entity Table

Revision ID: 6191e7644ff9
Revises: b1fa1db2596b
Create Date: 2026-05-17 06:35:28.374593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6191e7644ff9'
down_revision: Union[str, Sequence[str], None] = 'b1fa1db2596b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faulty_entity', sa.Column('entity_name', sa.String(), nullable=False))
    op.add_column('faulty_entity', sa.Column('part_number', sa.String(), nullable=False))
    op.add_column('faulty_entity', sa.Column('serial_number', sa.String(), nullable=False))
    op.add_column('faulty_entity', sa.Column('parent_entity_name', sa.String(), nullable=False))
    op.add_column('faulty_entity', sa.Column('confirmed_at', sa.String(), nullable=False))
    op.add_column('faulty_entity', sa.Column('investigation_notes', sa.String(), nullable=False))
    op.add_column('faulty_entity', sa.Column('created_at', sa.String(), nullable=False))
    op.add_column('faulty_entity', sa.Column('updated_at', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faulty_entity', 'updated_at')
    op.drop_column('faulty_entity', 'created_at')
    op.drop_column('faulty_entity', 'investigation_notes')
    op.drop_column('faulty_entity', 'confirmed_at')
    op.drop_column('faulty_entity', 'parent_entity_name')
    op.drop_column('faulty_entity', 'serial_number')
    op.drop_column('faulty_entity', 'part_number')
    op.drop_column('faulty_entity', 'entity_name')
    # ### end Alembic commands ###
