"""ConfigurationHistory table created to maintain history of items replaced of a given project 

Revision ID: 6e5f97c316ee
Revises: 9d0f485ddb15
Create Date: 2026-06-21 01:29:45.445870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5f97c316ee'
down_revision: Union[str, Sequence[str], None] = '9d0f485ddb15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
