"""Status column add in maintenance, faultyenityt, delivery tables

Revision ID: 6edd13c6c368
Revises: 3e9e1ea7d2a1
Create Date: 2026-06-20 16:59:58.067294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6edd13c6c368'
down_revision: Union[str, Sequence[str], None] = '3e9e1ea7d2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faulty_entity', sa.Column('status_id', sa.Integer(), nullable=True))
    op.add_column('maintenance_case', sa.Column('status_id', sa.Integer(), nullable=True))
    op.add_column('maintenance_delivery', sa.Column('status_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_delivery', 'status_id')
    op.drop_column('maintenance_case', 'status_id')
    op.drop_column('faulty_entity', 'status_id')
    # ### end Alembic commands ###
