"""faultyEntitytable updated

Revision ID: 7fe35679de66
Revises: 6159b971c73e
Create Date: 2026-06-15 04:10:17.313207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe35679de66'
down_revision: Union[str, Sequence[str], None] = '6159b971c73e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faulty_entity', sa.Column('hierarchy_parent_entity_id', sa.Integer(), nullable=True))
    op.add_column('faulty_entity', sa.Column('hierarchy_parent_entity_type', sa.Enum('PROJECT', 'SYSTEM', 'SUBSYSTEM', 'MODULE', 'UNIT', 'COMPONENT', 'ORDER', 'CUSTOMER', name='entitytype'), nullable=True))
    op.add_column('faulty_entity', sa.Column('depth', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faulty_entity', 'depth')
    op.drop_column('faulty_entity', 'hierarchy_parent_entity_type')
    op.drop_column('faulty_entity', 'hierarchy_parent_entity_id')
    # ### end Alembic commands ###
