"""Customer status-> status_name 

Revision ID: 9404410165fe
Revises: 3e4f7f03d99b
Create Date: 2026-06-19 21:21:38.164295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9404410165fe'
down_revision: Union[str, Sequence[str], None] = '3e4f7f03d99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('status_name', sa.String(), nullable=True))
    op.alter_column('customer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('customer', 'status')
    op.alter_column('order', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'order_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('order', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'order_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('order', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('customer', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('customer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # op.drop_column('customer', 'status_name')
    # ### end Alembic commands ###
