"""Customer Table  status: Optional[Status] = Relationship(back_populates=customers) 

Revision ID: 9547f723215b
Revises: ca8374af44da
Create Date: 2026-06-20 01:26:23.998018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9547f723215b'
down_revision: Union[str, Sequence[str], None] = 'ca8374af44da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('order', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'order_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('order', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('status', 'status_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('status', 'status_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'order_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('order', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
