"""maintainance action table fields updated

Revision ID: a2fa2807676d
Revises: 4fcbbb3eb6d5
Create Date: 2026-06-21 15:21:13.857912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2fa2807676d'
down_revision: Union[str, Sequence[str], None] = '4fcbbb3eb6d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_action', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('maintenance_action', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_action', 'updated_at')
    op.drop_column('maintenance_action', 'created_at')
    # ### end Alembic commands ###
