"""updted create maintenance case table and route

Revision ID: b04679f71757
Revises: 0cd15f8fecdb
Create Date: 2026-06-12 23:12:45.375446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b04679f71757'
down_revision: Union[str, Sequence[str], None] = '0cd15f8fecdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_case', sa.Column('project_name', sa.String(), nullable=True))
    op.add_column('maintenance_case', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('maintenance_case', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('maintenance_case', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_case', 'updated_at')
    op.drop_column('maintenance_case', 'created_at')
    op.drop_column('maintenance_case', 'resolved_at')
    op.drop_column('maintenance_case', 'project_name')
    # ### end Alembic commands ###
