"""Upgraded Maintenance table

Revision ID: b5d139903bb1
Revises: 7be9d2f53cb8
Create Date: 2026-05-18 23:50:02.902004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d139903bb1'
down_revision: Union[str, Sequence[str], None] = '7be9d2f53cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_case', sa.Column('entity_id', sa.Integer(), nullable=False))
    op.add_column('maintenance_case', sa.Column('entity_type', sa.String(), nullable=False))
    op.add_column('maintenance_case', sa.Column('part_number', sa.String(), nullable=False))
    op.alter_column('maintenance_case', 'case_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_maintenance_case_case_number'), table_name='maintenance_case')
    op.create_index(op.f('ix_maintenance_case_case_number'), 'maintenance_case', ['case_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_case_case_number'), table_name='maintenance_case')
    op.create_index(op.f('ix_maintenance_case_case_number'), 'maintenance_case', ['case_number'], unique=True)
    op.alter_column('maintenance_case', 'case_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('maintenance_case', 'part_number')
    op.drop_column('maintenance_case', 'entity_type')
    op.drop_column('maintenance_case', 'entity_id')
    # ### end Alembic commands ###
