"""Order table New fields added 

Revision ID: c9d2b228f0eb
Revises: a5b32833b3f7
Create Date: 2026-06-18 03:29:10.548186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9d2b228f0eb'
down_revision: Union[str, Sequence[str], None] = 'a5b32833b3f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('order', sa.Column('title', sa.String(), nullable=True))
    op.add_column('order', sa.Column('description', sa.String(), nullable=True))
    op.add_column('order', sa.Column('contract_number', sa.String(), nullable=True))
    op.add_column('order', sa.Column('po_number', sa.String(), nullable=True))
    op.add_column('order', sa.Column('order_date', sa.Date(), nullable=True))
    op.add_column('order', sa.Column('delivery_date', sa.Date(), nullable=True))
    op.add_column('order', sa.Column('total_value', sa.Numeric(), nullable=True))
    op.add_column('order', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('order', sa.Column('project_manager', sa.String(), nullable=True))
    op.add_column('order', sa.Column('remarks', sa.String(), nullable=True))
    op.create_index(op.f('ix_order_order_number'), 'order', ['order_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_order_number'), table_name='order')
    op.drop_column('order', 'remarks')
    op.drop_column('order', 'project_manager')
    op.drop_column('order', 'currency')
    op.drop_column('order', 'total_value')
    op.drop_column('order', 'delivery_date')
    op.drop_column('order', 'order_date')
    op.drop_column('order', 'po_number')
    op.drop_column('order', 'contract_number')
    op.drop_column('order', 'description')
    op.drop_column('order', 'title')
    op.alter_column('customer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('customer', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
