"""Customer table status_Name -> status_id Changed

Revision ID: ca8374af44da
Revises: 142959916d44
Create Date: 2026-06-19 22:54:02.288434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca8374af44da'
down_revision: Union[str, Sequence[str], None] = '142959916d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('status_id', sa.Integer(), nullable=True))
    op.alter_column('customer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('customer', 'status_name')
    op.alter_column('order', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'order_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('order', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('status', 'status_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('status', 'status_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'order_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('order', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('customer', sa.Column('status_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('customer', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('customer', 'status_id')
    # ### end Alembic commands ###
