"""changed m_status_id => status_id in maintenance, faultyenityt, delivery tables

Revision ID: d4b8dc472dda
Revises: 6edd13c6c368
Create Date: 2026-06-20 17:16:05.309029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b8dc472dda'
down_revision: Union[str, Sequence[str], None] = '6edd13c6c368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'faulty_entity', 'status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'maintenance_case', 'status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'maintenance_delivery', 'status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'maintenance_delivery', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_case', type_='foreignkey')
    op.drop_constraint(None, 'faulty_entity', type_='foreignkey')
    # ### end Alembic commands ###
