"""updted new files

Revision ID: d671fa45ec45
Revises: b04679f71757
Create Date: 2026-06-13 12:42:16.447165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd671fa45ec45'
down_revision: Union[str, Sequence[str], None] = 'b04679f71757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_case', 'project_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_case', sa.Column('project_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    # ### end Alembic commands ###
